[tools]
java = "temurin-21.0.8+9.0.LTS"
gradle = "9.0.0"

[tasks.version-catalog-update]
run = "./gradlew versionCatalogUpdate --interactive --no-configuration-cache"
description = "Update version catalog dependencies"
